import type { NormalizedMessage, NormalizedContentBlock } from '../providers/types';

function splitAtNewline(text: string, index: number, direction: 'forward' | 'backward'): number {
  if (direction === 'forward') {
    const nl = text.indexOf('\n', index);
    return nl === -1 ? index : nl;
  } else {
    const nl = text.lastIndexOf('\n', index);
    return nl === -1 ? index : nl;
  }
}

/**
 * Safely trims the message history to avoid exceeding context window limits,
 * while ensuring tool_use / tool_result pairs are never orphaned.
 */
export function trimMessages(
  messages: NormalizedMessage[],
  maxMessages: number = 25
): NormalizedMessage[] {
  if (messages.length <= maxMessages) return messages;

  const firstMessage = messages[0];
  const targetTailLength = maxMessages - 1;
  const startIndex = messages.length - targetTailLength;

  let trimmableMessages = messages.slice(startIndex);
  let currentIndex = startIndex;

  let expansions = 0;
  // Ensure we didn't orphan a tool_result by leaving it at the front
  // without its corresponding assistant tool_use message.
  while (trimmableMessages.length > 0 && expansions < 20) {
    const first = trimmableMessages[0];
    if (first.role === 'user' && Array.isArray(first.content)) {
      const hasToolResult = first.content.some((c: any) => c.type === 'tool_result');
      if (hasToolResult) {
        if (currentIndex > 1) {
          currentIndex--;
          trimmableMessages.unshift(messages[currentIndex]);
          expansions++;
          continue;
        }
      }
    }
    break; // Safe boundary reached
  }

  return [firstMessage, ...trimmableMessages];
}

/**
 * Gets the standard system instruction for the executor.
 */
export function getExecutorSystemInstruction(): string {
  return `You are the Execution Engine of the Ceobe AI System.
Your task is to take the provided execution plan and strictly implement it.
You have access to tool commands to read/write files and run terminal commands.
DO NOT provide planning commentary. DO NOT hallucinate dependencies. Write code.
When you are completely finished with the task, you MUST call the finish_task tool.
If you need architectural or design context, use read_file to read .ceobe/architecture.md or .ceobe/design.md.`;
}

/**
 * Truncates massive text blocks generated by the model to prevent blowing up the context.
 */
export function truncateModelResponse(content: NormalizedContentBlock[], limit: number = 4000): NormalizedContentBlock[] {
  return content.map(c => {
    if (c.type === 'text' && 'text' in c && typeof c.text === 'string' && c.text.length > limit) {
       const headIdx = splitAtNewline(c.text, Math.floor(limit / 2), 'backward');
       const tailIdx = splitAtNewline(c.text, c.text.length - Math.floor(limit / 2), 'forward');
       const head = c.text.substring(0, headIdx);
       const tail = c.text.substring(tailIdx);
       return { ...c, text: head + '\n\n...[Reasoning Truncated]...\n\n' + tail };
    }
    return c;
  });
}

/**
 * Truncates massive tool results before sending them to the model.
 */
export function truncateToolResult(resultPayload: unknown, limit: number = 8000): string | NormalizedContentBlock[] {
  let resultBlocks: string | NormalizedContentBlock[];
  let resultStr: string;

  if (Array.isArray(resultPayload)) {
    resultBlocks = resultPayload;
    resultStr = JSON.stringify(resultBlocks);
  } else {
    resultStr = String(resultPayload);
    resultBlocks = resultStr;
  }

  if (resultStr.length > limit) {
    if (Array.isArray(resultPayload)) {
      return resultPayload.map((b: NormalizedContentBlock) => {
         if (b.type === 'text' && typeof b.text === 'string' && b.text.length > limit) {
           const headIdx = splitAtNewline(b.text, Math.floor(limit / 2), 'backward');
           const tailIdx = splitAtNewline(b.text, b.text.length - Math.floor(limit / 2), 'forward');
           return { ...b, text: b.text.substring(0, headIdx) + "\n\n...[TRUNCATED BY CEOBE]...\n\n" + b.text.substring(tailIdx) };
         }
         return b;
      });
    } else {
      const headIdx = splitAtNewline(resultStr, Math.floor(limit / 2), 'backward');
      const tailIdx = splitAtNewline(resultStr, resultStr.length - Math.floor(limit / 2), 'forward');
      return resultStr.substring(0, headIdx) + "\n\n...[TRUNCATED BY CEOBE]...\n\n" + resultStr.substring(tailIdx);
    }
  }

  return resultBlocks;
}

/**
 * Cleans up old self-heal directives from previous tool_results.
 */
export function cleanupOldSelfHeals(messages: NormalizedMessage[]): NormalizedMessage[] {
  return messages.map(msg => {
    if (msg.role === 'user' && Array.isArray(msg.content)) {
      return {
        ...msg,
        content: msg.content.map((c: any) => {
          if (c.type === 'tool_result' && typeof c.content === 'string') {
             return { ...c, content: c.content.replace(/\[SELF-HEAL \d+\/\d+\].*/g, '[Older Self-Heal Omitted]') };
          }
          return c;
        })
      };
    }
    return msg;
  });
}
